language: scala

scala:
   - 2.11.8
#   - 2.12.0
#   - 2.12.1

sudo: required

services:
  - docker

before_install:
    - docker info
    - sudo service docker stop
    - sudo echo 'DOCKER_OPTS="-H 127.0.0.1:55555"' | sudo tee /etc/default/docker
    - sudo service docker start
    - sudo cat /etc/default/docker
