language: scala

scala:
   - 2.11.8
#   - 2.12.0
#   - 2.12.1

sudo: required

services:
  - docker

before_install:
    - sudo service docker stop
    - sudo echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock"' | sudo tee /etc/default/docker
    - sudo service docker start
    - sudo service docker status
    - sudo cat /etc/default/docker
    - sudo docker pull mysql:5.6
    - sudo docker pull hello-world
